// Mocks generated by Mockito 5.3.2 from annotations
// in clean_architecture/test/domain_layer/usecases/fetch_producrs_uc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_architecture/domain_layer/entities/product_response_entity.dart'
    as _i2;
import 'package:clean_architecture/domain_layer/repositories/products_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductResponseEntity_0 extends _i1.SmartFake
    implements _i2.ProductResponseEntity {
  _FakeProductResponseEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i3.ProductsRepository {
  @override
  _i4.Future<_i2.ProductResponseEntity> fetchProducts() => (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [],
        ),
        returnValue: _i4.Future<_i2.ProductResponseEntity>.value(
            _FakeProductResponseEntity_0(
          this,
          Invocation.method(
            #fetchProducts,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.ProductResponseEntity>.value(
            _FakeProductResponseEntity_0(
          this,
          Invocation.method(
            #fetchProducts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ProductResponseEntity>);
  @override
  dynamic updateProducts(String? productId) => super.noSuchMethod(
        Invocation.method(
          #updateProducts,
          [productId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic deleteProducts(String? productId) => super.noSuchMethod(
        Invocation.method(
          #deleteProducts,
          [productId],
        ),
        returnValueForMissingStub: null,
      );
}
